// <auto-generated />
namespace Academy_Control.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Criaçãodobanco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Criaçãodobanco));
        
        string IMigrationMetadata.Id
        {
            get { return "201710050215213_Criação do banco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
